name: Deployment
on:
  push:
    branches:
      - main
      - development
env: #these will be available to all jobs
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    env: #only available in this job
      MONGODB_CLUSTER_ADDRESS: cluster0.hu2mt.mongodb.net
      MONGODB_USERNAME: pepemtzcampos
      MONGODB_PASSWORD: tabiRClKUWO45c2y
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2
      - name: Cache dependencies
        uses: actions/cache@v4.1.2
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # Linux Syntax
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}" # Github Actions Syntax
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |   
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"  # This should not be available     
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}" # This is available
